FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG TARGETARCH

# Install system dependencies for confluent-kafka (C-bindings) and PySpark (Java)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    g++ \
    librdkafka-dev \
    default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/"*"

# Set Java Home for PySpark
ENV JAVA_HOME=/usr/lib/jvm/default-java

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src/
COPY config/ /app/config/
